'use strict';
// Year workbook export (Excel) — the browser twin of close_engine/excel.py.
// Same sheets, same cells, same formulas; tests/test_excel_parity.py compares the two cell for cell.
// Works in the browser (window.ExcelJS from vendor/exceljs.min.js) and in Node (require('exceljs')).
(function () {
  const M = window.MEC;
  const MONEY = '#,##0.00;(#,##0.00);"-"';
  const BOLD = { bold: true };
  const HEAD = { bold: true, color: { argb: 'FFFFFFFF' } };
  const HEAD_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2F5D50' } };
  const SUB_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE7F0EC' } };
  const TOP = { top: { style: 'thin' } };
  const d = cents => cents / 100;
  const col = n => { let s = ''; for (; n > 0; n = Math.floor((n - 1) / 26)) s = String.fromCharCode(65 + ((n - 1) % 26)) + s; return s; };
  const f = text => ({ formula: text });

  function put(ws, row, column, value, style = {}) {
    const cell = ws.getCell(row, column);
    cell.value = value;
    if (style.money) cell.numFmt = MONEY;
    if (style.font) cell.font = style.font;
    if (style.fill) cell.fill = style.fill;
    if (style.border) cell.border = style.border;
    if (style.align) cell.alignment = { horizontal: style.align };
    return cell;
  }
  function header(ws, row, labels) {
    labels.forEach((label, i) => put(ws, row, i + 1, label, { font: HEAD, fill: HEAD_FILL, align: i ? 'center' : 'left' }));
  }
  function widths(ws, list) { list.forEach((w, i) => { ws.getColumn(i + 1).width = w; }); }

  // closed = [{ period, books, result }, …] consecutive closed months; ys = M.yearStatements(closed)
  M.buildYearWorkbook = function (ExcelJS, closed, ys) {
    const wb = new ExcelJS.Workbook();
    const months = ys.months, n = months.length;
    const short = p => M.periodLabel(p).slice(0, 3);

    // ---------- Summary ----------
    let ws = wb.addWorksheet('Summary');
    put(ws, 1, 1, `${M.SETUP.company} – FY ${M.YEAR}`, { font: { bold: true, size: 14 } });
    put(ws, 2, 1, `${M.periodLabel(ys.firstPeriod)} to ${M.periodLabel(ys.lastPeriod)} · ${n} closed months · generated by the close engine`);
    header(ws, 4, ['Month', 'Verdict', 'Net sales', 'Net income', 'Cash – Bank', 'Warnings', 'Period seal']);
    closed.forEach((c, i) => {
      const r = c.result, row = 5 + i;
      put(ws, row, 1, M.periodLabel(c.period));
      put(ws, row, 2, r.verdict);
      put(ws, row, 3, d(r.statements.netSales), { money: true });
      put(ws, row, 4, d(r.statements.netIncome), { money: true });
      put(ws, row, 5, d(M.acctSum(r.ledger, '1000')), { money: true });
      put(ws, row, 6, r.counts.warn);
      put(ws, row, 7, r.lock.inputHash);
    });
    const last = 4 + closed.length, tot = last + 1;
    put(ws, tot, 1, 'FY total', { font: BOLD });
    for (const c of [3, 4]) put(ws, tot, c, f(`SUM(${col(c)}5:${col(c)}${last})`), { money: true, font: BOLD, border: TOP });
    put(ws, tot + 2, 1, 'Year checks', { font: BOLD });
    [
      ['Opening equity', d(ys.openingEquity)],
      ['+ Net income, year to date', f(`D${tot}`)],
      ['− Closing equity', d(ys.closing.totalEquity)],
      ['= Difference (must be 0)', f(`B${tot + 3}+B${tot + 4}-B${tot + 5}`)],
      ['Closing balance sheet difference (must be 0)', d(ys.closing.bsDiff)],
    ].forEach(([label, value], i) => { put(ws, tot + 3 + i, 1, label); put(ws, tot + 3 + i, 2, value, { money: true }); });
    widths(ws, [44, 22, 16, 16, 16, 10, 20]);

    // ---------- Income statement: a column per month + a formula total ----------
    ws = wb.addWorksheet('Income Statement', { views: [{ state: 'frozen', xSplit: 1, ySplit: 3 }] });
    put(ws, 1, 1, `Income statement · FY ${M.YEAR}`, { font: { bold: true, size: 13 } });
    header(ws, 3, ['Line'].concat(months.map(m => short(m.period)), ['FY total']));
    const firstCol = 'B', lastCol = col(n + 1);
    let row = 4;
    const refs = {};
    const valueRow = (label, values, key) => {
      put(ws, row, 1, label);
      values.forEach((v, j) => put(ws, row, j + 2, d(v), { money: true }));
      put(ws, row, n + 2, f(`SUM(${firstCol}${row}:${lastCol}${row})`), { money: true, font: BOLD });
      if (key) refs[key] = row;
      row++;
    };
    const formulaRow = (label, build, key) => {
      const style = { font: BOLD, fill: SUB_FILL, border: TOP };
      put(ws, row, 1, label, style);
      for (let j = 2; j <= n + 2; j++) put(ws, row, j, f(build(col(j))), { ...style, money: true });
      refs[key] = row;
      row++;
    };
    const lines = code => months.map(m => m.lines[code]);
    valueRow('Book sales', lines('4000'), '4000');
    valueRow('Café sales', lines('4010'), '4010');
    valueRow('Sales returns', lines('4100'), '4100'); // already negative: a contra-revenue account
    formulaRow('Net sales', L => `${L}${refs['4000']}+${L}${refs['4010']}+${L}${refs['4100']}`, 'sales');
    const cogs = ['5000', '5010', '5020', '5030'];
    for (const code of cogs) valueRow(M.acct(code).name, lines(code).map(v => -v), code);
    formulaRow('Gross profit', L => `${L}${refs.sales}+` + cogs.map(c => `${L}${refs[c]}`).join('+'), 'gp');
    const opex = ['6000', '6100', '6200', '6300', '6400', '6410', '6500', '6600', '6700'];
    for (const code of opex) valueRow(M.acct(code).name, lines(code).map(v => -v), code);
    formulaRow('Operating income', L => `${L}${refs.gp}+` + opex.map(c => `${L}${refs[c]}`).join('+'), 'op');
    valueRow('Interest income', lines('4900'), '4900');
    valueRow('Interest expense', lines('7000').map(v => -v), '7000');
    formulaRow('Net income', L => `${L}${refs.op}+${L}${refs['4900']}+${L}${refs['7000']}`, 'ni');
    put(ws, row + 1, 1, 'Check: net income per the close engine');
    months.forEach((m, j) => put(ws, row + 1, j + 2, d(m.st.netIncome), { money: true }));
    put(ws, row + 1, n + 2, d(ys.totals.netIncome), { money: true });
    widths(ws, [30].concat(months.map(() => 13), [15]));

    // ---------- Balance sheet: 1 January vs latest close ----------
    ws = wb.addWorksheet('Balance Sheet');
    const o = ys.opening, c = ys.closing;
    put(ws, 1, 1, `Balance sheet · 1 January vs ${M.periodLabel(ys.lastPeriod)} month end`, { font: { bold: true, size: 13 } });
    header(ws, 3, ['Account', '1 Jan', M.periodLabel(ys.lastPeriod), 'Change']);
    row = 4;
    const bsBlock = (title, key) => {
      put(ws, row, 1, title, { font: BOLD });
      row++;
      const start = row;
      const codes = [...new Set(o[key].concat(c[key]).map(r => r.code))].filter(x => x !== '3100').sort();
      const amt = (st, code) => (st[key].find(r => r.code === code) || { amount: 0 }).amount;
      for (const code of codes) {
        put(ws, row, 1, M.acct(code).name);
        put(ws, row, 2, d(amt(o, code)), { money: true });
        put(ws, row, 3, d(amt(c, code)), { money: true });
        put(ws, row, 4, f(`C${row}-B${row}`), { money: true });
        row++;
      }
      return start;
    };
    const total = (label, fb, fc) => {
      const style = { font: BOLD, fill: SUB_FILL, border: TOP };
      put(ws, row, 1, label, style);
      put(ws, row, 2, f(fb), { ...style, money: true });
      put(ws, row, 3, f(fc), { ...style, money: true });
      put(ws, row, 4, f(`C${row}-B${row}`), { ...style, money: true });
      return row++;
    };
    let s = bsBlock('Assets', 'assets');
    const ta = total('Total assets', `SUM(B${s}:B${row - 1})`, `SUM(C${s}:C${row - 1})`);
    s = bsBlock('Liabilities', 'liabilities');
    const tl = total('Total liabilities', `SUM(B${s}:B${row - 1})`, `SUM(C${s}:C${row - 1})`);
    s = bsBlock('Equity', 'equity');
    const reOpen = (o.equity.find(r => r.code === '3100') || { amount: 0 }).amount;
    for (const [label, b, cc] of [['Retained earnings at 1 January', reOpen, reOpen], ['Net income, year to date', 0, ys.totals.netIncome]]) {
      put(ws, row, 1, label);
      put(ws, row, 2, d(b), { money: true });
      put(ws, row, 3, d(cc), { money: true });
      put(ws, row, 4, f(`C${row}-B${row}`), { money: true });
      row++;
    }
    const te = total('Total equity', `SUM(B${s}:B${row - 1})`, `SUM(C${s}:C${row - 1})`);
    total('Liabilities + equity', `B${tl}+B${te}`, `C${tl}+C${te}`);
    total('Check: assets − (liabilities + equity)', `B${ta}-B${tl}-B${te}`, `C${ta}-C${tl}-C${te}`);
    widths(ws, [40, 16, 18, 16]);

    // ---------- Trial balance at the latest close ----------
    ws = wb.addWorksheet('Trial Balance');
    const tb = M.trialBalance(closed[closed.length - 1].result.ledger);
    put(ws, 1, 1, `Trial balance · ${M.periodLabel(ys.lastPeriod)} after the month-end close`, { font: { bold: true, size: 13 } });
    header(ws, 3, ['Account', 'Name', 'Debit', 'Credit']);
    tb.rows.forEach((r, i) => {
      put(ws, 4 + i, 1, r.code);
      put(ws, 4 + i, 2, r.name);
      put(ws, 4 + i, 3, r.dr ? d(r.dr) : null, { money: true });
      put(ws, 4 + i, 4, r.cr ? d(r.cr) : null, { money: true });
    });
    const end = 3 + tb.rows.length;
    put(ws, end + 1, 2, 'Total', { font: BOLD, border: TOP });
    put(ws, end + 1, 3, f(`SUM(C4:C${end})`), { money: true, font: BOLD, border: TOP });
    put(ws, end + 1, 4, f(`SUM(D4:D${end})`), { money: true, font: BOLD, border: TOP });
    put(ws, end + 2, 2, 'Difference (must be 0)');
    put(ws, end + 2, 3, f(`C${end + 1}-D${end + 1}`), { money: true });
    widths(ws, [10, 32, 16, 16]);

    // ---------- Journal: every line of every entry, all months ----------
    ws = wb.addWorksheet('Journal', { views: [{ state: 'frozen', ySplit: 1 }] });
    header(ws, 1, ['Month', 'Entry', 'Date', 'Description', 'Source', 'Account', 'Account name', 'Debit', 'Credit']);
    row = 2;
    for (const cm of closed) {
      for (const je of cm.result.ledger) {
        for (const l of je.lines) {
          [cm.period, je.id, je.date, je.memo, je.source, l.acct, M.acct(l.acct).name, l.dr ? d(l.dr) : null, l.cr ? d(l.cr) : null]
            .forEach((v, k) => put(ws, row, k + 1, v, k >= 7 ? { money: true } : {}));
          row++;
        }
      }
    }
    put(ws, row, 7, 'Total', { font: BOLD });
    for (const cc of [8, 9]) put(ws, row, cc, f(`SUM(${col(cc)}2:${col(cc)}${row - 1})`), { money: true, font: BOLD });
    ws.autoFilter = `A1:I${row - 1}`;
    widths(ws, [9, 10, 11, 46, 11, 9, 28, 14, 14]);

    // ---------- Close log: the nine steps and findings per month ----------
    ws = wb.addWorksheet('Close Log', { views: [{ state: 'frozen', ySplit: 1 }] });
    header(ws, 1, ['Month', 'Step', 'Result', 'Summary']);
    row = 2;
    for (const cm of closed) {
      for (const stp of cm.result.steps) {
        [cm.period, `${stp.n}. ${stp.title}`, stp.ok ? 'Tied' : 'EXCEPTION', stp.summary].forEach((v, k) => put(ws, row, k + 1, v));
        row++;
      }
      for (const fnd of cm.result.findings) {
        [cm.period, `${fnd.control} ${fnd.severity}`, fnd.message, fnd.detail].forEach((v, k) => put(ws, row, k + 1, v, { font: { italic: true } }));
        row++;
      }
    }
    widths(ws, [9, 38, 30, 110]);
    return wb;
  };
})();
