"""Export a closed year to an Excel workbook an accountant can audit.

Values are written in dollars; totals and checks are live Excel formulas, so the workbook
recalculates if someone edits a figure.
"""
from __future__ import annotations

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from .close import YEAR_LINES, acct_sum, trial_balance
from .core import SETUP, YEAR, acct, period_label

MONEY = '#,##0.00;(#,##0.00);"-"'
BOLD = Font(bold=True)
HEAD = Font(bold=True, color="FFFFFF")
HEAD_FILL = PatternFill("solid", fgColor="2F5D50")
SUB_FILL = PatternFill("solid", fgColor="E7F0EC")
TOP = Border(top=Side(style="thin"))


def _d(cents: int) -> float:
    return cents / 100


def _header(ws, row: int, labels: list[str]) -> None:
    for i, label in enumerate(labels, start=1):
        c = ws.cell(row=row, column=i, value=label)
        c.font, c.fill = HEAD, HEAD_FILL
        c.alignment = Alignment(horizontal="center" if i > 1 else "left")


def _widths(ws, widths: list[int]) -> None:
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def export_year(closed: list[dict], ys: dict, path: str) -> str:
    wb = Workbook()
    months = ys["months"]
    n = len(months)
    short = lambda p: period_label(p).split(" ")[0][:3]

    # ---------- Summary ----------
    ws = wb.active
    ws.title = "Summary"
    ws["A1"] = f"{SETUP['company']} – FY {YEAR}"
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"] = f"{period_label(ys['firstPeriod'])} to {period_label(ys['lastPeriod'])} · {n} closed months · generated by the close engine"
    _header(ws, 4, ["Month", "Verdict", "Net sales", "Net income", "Cash – Bank", "Warnings", "Period seal"])
    for i, c in enumerate(closed, start=5):
        r = c["result"]
        ws.cell(row=i, column=1, value=period_label(c["period"]))
        ws.cell(row=i, column=2, value=r["verdict"])
        ws.cell(row=i, column=3, value=_d(r["statements"]["netSales"])).number_format = MONEY
        ws.cell(row=i, column=4, value=_d(r["statements"]["netIncome"])).number_format = MONEY
        ws.cell(row=i, column=5, value=_d(acct_sum(r["ledger"], "1000"))).number_format = MONEY
        ws.cell(row=i, column=6, value=r["counts"]["warn"])
        ws.cell(row=i, column=7, value=r["lock"]["inputHash"])
    last = 4 + len(closed)
    tot = last + 1
    ws.cell(row=tot, column=1, value="FY total").font = BOLD
    for col in (3, 4):
        L = get_column_letter(col)
        c = ws.cell(row=tot, column=col, value=f"=SUM({L}5:{L}{last})")
        c.number_format, c.font, c.border = MONEY, BOLD, TOP
    ws.cell(row=tot + 2, column=1, value="Year checks").font = BOLD
    checks = [
        ("Opening equity", _d(ys["openingEquity"])),
        ("+ Net income, year to date", f"=D{tot}"),
        ("− Closing equity", _d(ys["closing"]["totalEquity"])),
        ("= Difference (must be 0)", f"=B{tot + 3}+B{tot + 4}-B{tot + 5}"),
        ("Closing balance sheet difference (must be 0)", _d(ys["closing"]["bsDiff"])),
    ]
    for i, (label, value) in enumerate(checks, start=tot + 3):
        ws.cell(row=i, column=1, value=label)
        ws.cell(row=i, column=2, value=value).number_format = MONEY
    _widths(ws, [44, 22, 16, 16, 16, 10, 20])

    # ---------- Income statement: a column per month + a formula total ----------
    ws = wb.create_sheet("Income Statement")
    ws["A1"] = f"Income statement · FY {YEAR}"
    ws["A1"].font = Font(bold=True, size=13)
    _header(ws, 3, ["Line"] + [short(m["period"]) for m in months] + ["FY total"])
    total_col = get_column_letter(n + 2)
    first_col, last_col = "B", get_column_letter(n + 1)
    row = 4
    refs: dict[str, int] = {}

    def value_row(label: str, values: list[int], key: str | None = None) -> None:
        nonlocal row
        ws.cell(row=row, column=1, value=label)
        for j, v in enumerate(values, start=2):
            ws.cell(row=row, column=j, value=_d(v)).number_format = MONEY
        c = ws.cell(row=row, column=n + 2, value=f"=SUM({first_col}{row}:{last_col}{row})")
        c.number_format, c.font = MONEY, BOLD
        if key:
            refs[key] = row
        row += 1

    def formula_row(label: str, build, key: str) -> None:
        nonlocal row
        cells = [ws.cell(row=row, column=1, value=label)]
        for j in range(2, n + 3):
            L = get_column_letter(j)
            cells.append(ws.cell(row=row, column=j, value="=" + build(L)))
            cells[-1].number_format = MONEY
        for c in cells:
            c.font, c.fill, c.border = BOLD, SUB_FILL, TOP
        refs[key] = row
        row += 1

    lines = lambda code: [m["lines"][code] for m in months]
    value_row("Book sales", lines("4000"), "4000")
    value_row("Café sales", lines("4010"), "4010")
    value_row("Sales returns", lines("4100"), "4100")  # already negative: a contra-revenue account
    formula_row("Net sales", lambda L: f"{L}{refs['4000']}+{L}{refs['4010']}+{L}{refs['4100']}", "sales")
    for code in ("5000", "5010", "5020", "5030"):
        value_row(acct(code)["name"], [-v for v in lines(code)], code)
    formula_row("Gross profit", lambda L: f"{L}{refs['sales']}+" + "+".join(f"{L}{refs[c]}" for c in ("5000", "5010", "5020", "5030")), "gp")
    opex = ["6000", "6100", "6200", "6300", "6400", "6410", "6500", "6600", "6700"]
    for code in opex:
        value_row(acct(code)["name"], [-v for v in lines(code)], code)
    formula_row("Operating income", lambda L: f"{L}{refs['gp']}+" + "+".join(f"{L}{refs[c]}" for c in opex), "op")
    value_row("Interest income", lines("4900"), "4900")
    value_row("Interest expense", [-v for v in lines("7000")], "7000")
    formula_row("Net income", lambda L: f"{L}{refs['op']}+{L}{refs['4900']}+{L}{refs['7000']}", "ni")
    ws.cell(row=row + 1, column=1, value="Check: net income per the close engine")
    for j, m in enumerate(months, start=2):
        ws.cell(row=row + 1, column=j, value=_d(m["st"]["netIncome"])).number_format = MONEY
    ws.cell(row=row + 1, column=n + 2, value=_d(ys["totals"]["netIncome"])).number_format = MONEY
    _widths(ws, [30] + [13] * n + [15])
    ws.freeze_panes = "B4"

    # ---------- Balance sheet: 1 January vs latest close ----------
    ws = wb.create_sheet("Balance Sheet")
    o, c = ys["opening"], ys["closing"]
    ws["A1"] = f"Balance sheet · 1 January vs {period_label(ys['lastPeriod'])} month end"
    ws["A1"].font = Font(bold=True, size=13)
    _header(ws, 3, ["Account", "1 Jan", period_label(ys["lastPeriod"]), "Change"])
    row = 4

    def bs_block(title: str, key: str) -> int:
        nonlocal row
        ws.cell(row=row, column=1, value=title).font = BOLD
        row += 1
        start = row
        codes = sorted({r["code"] for r in o[key] + c[key]} - {"3100"})
        amt = lambda st, code: next((r["amount"] for r in st[key] if r["code"] == code), 0)
        for code in codes:
            ws.cell(row=row, column=1, value=acct(code)["name"])
            ws.cell(row=row, column=2, value=_d(amt(o, code))).number_format = MONEY
            ws.cell(row=row, column=3, value=_d(amt(c, code))).number_format = MONEY
            ws.cell(row=row, column=4, value=f"=C{row}-B{row}").number_format = MONEY
            row += 1
        return start

    def total(label: str, formula_b: str, formula_c: str) -> int:
        nonlocal row
        for col, val in ((1, label), (2, formula_b), (3, formula_c), (4, f"=C{row}-B{row}")):
            cell = ws.cell(row=row, column=col, value=val)
            cell.font, cell.fill, cell.border = BOLD, SUB_FILL, TOP
            if col > 1:
                cell.number_format = MONEY
        row += 1
        return row - 1

    s = bs_block("Assets", "assets")
    ta = total("Total assets", f"=SUM(B{s}:B{row - 1})", f"=SUM(C{s}:C{row - 1})")
    s = bs_block("Liabilities", "liabilities")
    tl = total("Total liabilities", f"=SUM(B{s}:B{row - 1})", f"=SUM(C{s}:C{row - 1})")
    s = bs_block("Equity", "equity")
    re_open = next((r["amount"] for r in o["equity"] if r["code"] == "3100"), 0)
    for label, b, cc in (("Retained earnings at 1 January", re_open, re_open), ("Net income, year to date", 0, ys["totals"]["netIncome"])):
        ws.cell(row=row, column=1, value=label)
        ws.cell(row=row, column=2, value=_d(b)).number_format = MONEY
        ws.cell(row=row, column=3, value=_d(cc)).number_format = MONEY
        ws.cell(row=row, column=4, value=f"=C{row}-B{row}").number_format = MONEY
        row += 1
    te = total("Total equity", f"=SUM(B{s}:B{row - 1})", f"=SUM(C{s}:C{row - 1})")
    total("Liabilities + equity", f"=B{tl}+B{te}", f"=C{tl}+C{te}")
    total("Check: assets − (liabilities + equity)", f"=B{ta}-B{tl}-B{te}", f"=C{ta}-C{tl}-C{te}")
    _widths(ws, [40, 16, 18, 16])

    # ---------- Trial balance at the latest close ----------
    ws = wb.create_sheet("Trial Balance")
    tb = trial_balance(closed[-1]["result"]["ledger"])
    ws["A1"] = f"Trial balance · {period_label(ys['lastPeriod'])} after the month-end close"
    ws["A1"].font = Font(bold=True, size=13)
    _header(ws, 3, ["Account", "Name", "Debit", "Credit"])
    for i, r in enumerate(tb["rows"], start=4):
        ws.cell(row=i, column=1, value=r["code"])
        ws.cell(row=i, column=2, value=r["name"])
        ws.cell(row=i, column=3, value=_d(r["dr"]) or None).number_format = MONEY
        ws.cell(row=i, column=4, value=_d(r["cr"]) or None).number_format = MONEY
    end = 3 + len(tb["rows"])
    for col, val in ((2, "Total"), (3, f"=SUM(C4:C{end})"), (4, f"=SUM(D4:D{end})")):
        cell = ws.cell(row=end + 1, column=col, value=val)
        cell.font, cell.border = BOLD, TOP
        if col > 2:
            cell.number_format = MONEY
    ws.cell(row=end + 2, column=2, value="Difference (must be 0)")
    ws.cell(row=end + 2, column=3, value=f"=C{end + 1}-D{end + 1}").number_format = MONEY
    _widths(ws, [10, 32, 16, 16])

    # ---------- Journal: every line of every entry, all months ----------
    ws = wb.create_sheet("Journal")
    _header(ws, 1, ["Month", "Entry", "Date", "Description", "Source", "Account", "Account name", "Debit", "Credit"])
    row = 2
    for cm in closed:
        for je in cm["result"]["ledger"]:
            for l in je["lines"]:
                for col, val in enumerate([cm["period"], je["id"], je["date"], je["memo"], je["source"], l["acct"],
                                           acct(l["acct"])["name"], _d(l["dr"]) or None, _d(l["cr"]) or None], start=1):
                    cell = ws.cell(row=row, column=col, value=val)
                    if col >= 8:
                        cell.number_format = MONEY
                row += 1
    ws.cell(row=row, column=7, value="Total").font = BOLD
    for col in (8, 9):
        L = get_column_letter(col)
        cell = ws.cell(row=row, column=col, value=f"=SUM({L}2:{L}{row - 1})")
        cell.number_format, cell.font = MONEY, BOLD
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:I{row - 1}"
    _widths(ws, [9, 10, 11, 46, 11, 9, 28, 14, 14])

    # ---------- Close log: the nine steps and findings per month ----------
    ws = wb.create_sheet("Close Log")
    _header(ws, 1, ["Month", "Step", "Result", "Summary"])
    row = 2
    for cm in closed:
        for stp in cm["result"]["steps"]:
            for col, val in enumerate([cm["period"], f"{stp['n']}. {stp['title']}", "Tied" if stp["ok"] else "EXCEPTION", stp["summary"]], start=1):
                ws.cell(row=row, column=col, value=val)
            row += 1
        for fnd in cm["result"]["findings"]:
            for col, val in enumerate([cm["period"], f"{fnd['control']} {fnd['severity']}", fnd["message"], fnd["detail"]], start=1):
                ws.cell(row=row, column=col, value=val).font = Font(italic=True)
            row += 1
    ws.freeze_panes = "A2"
    _widths(ws, [9, 38, 30, 110])

    wb.save(path)
    return path
